<?php
$array = [
    [
        'name'   => 'Git yüklə',
        'img_url'=> '',
        'izah'   => 'Git yükləmək üçün aşağıdakı linkdən istifadə edə bilərsiniz',
        'ulink'  => ['https://git-scm.com/downloads','https://git-scm.com/downloads']
    ] ,
    [
        'name' => 'git --version',
        'img_url' => './assets\img\MScreenshot-2022-02-23-220146.png',
        'izah' => 'Komputerinizdə yüklü olan git versiyasını yoxlamaq üçün <b><i> git --version </i></b> yazırıq.',
        'ulink' => '',
    ],
    [
        'name'   => 'git config --global user.name "userName"',
        'img_url' => '',
        'izah'   => 'Komputerinizdə git hesabı yaratmaq üçün user name daxil edirsiniz və əlavə olaraq <b><i> git config --global user.email "userEmail" </i></b> daxil edərək sisteminizdə edilən dəyişiklikləri bu hesabınızla izləyə bilərsiniz',
        'ulink'  => [],
    ],
    [
        'name'   => 'git config --global user.name',
        'img_url' => './assets\img\M2Screenshot-2022-02-23-223007.png',
        'izah'   => 'Bu əmri yazaraq sistemimizdəki git dəyişiklikləri hansı user name ilə saxlanır onu görə bilərik. Eynilə, <b><i> git config --global user.email </i></b> ilə hansı email hesabı istifadə etdiyimizi də yoxlaya bilərik.',
        'ulink'  => [],
    ],

    [
        'name'   => 'pwd',
        'img_url' => './assets\img\Screenshot-2022-02-23-044328.png',
        'izah'   => 'Print working directory, hal hazırda hansı folder daxilindəyiksə onu göstərir.',
        'ulink'  => [],
    ],
    [
        'name'   => 'clear',
        'img_url' => './assets\img\Screenshot-2022-02-23-044408.png',
        'izah'   => 'Ekranı təmizləmək üçün istifadə olunur, <b><i> CTRL + L </i></b> kombinasiyası ilə də çalışma mühitindəki (Terminaldakı) kodları təmizləyə bilərik.',
        'ulink'  => [],
    ],
    [
        'name'   => 'ls',
        'img_url' => './assets\img\Screenshot-2022-02-23-044431.png',
        'izah'   => 'olduğumuz folder daxilindəki folder və faylların listini verir',
        'ulink'  => [],
    ],
    [
        'name'   => 'ls -a',
        'img_url' => '',
        'izah'   => 'gizli folder və ya faylları listələmək üçün bu əmrdən istifadə edirik',
        'ulink'  => [],
    ],
    [
        'name'   => 'cd ..',
        'img_url' => './assets\img\Screenshot-2022-02-23-044515.png',
        'izah'   => 'Hazırki qovluqdan çıxmaq üçün istifadə olunur',
        'ulink'  => [],
    ],
    [
        'name'   => 'cd folderName',
        'img_url' => './assets\img\Screenshot-2022-02-23-044614.png',
        'izah'   => 'bu əmri istifadə edərək folderə daxil oluruq',
        'ulink'  => [],
    ],
    [
        'name'   => 'mkdir folderName',
        'img_url' => './assets\img\Screenshot-2022-02-23-044643.png',
        'izah'   => 'mkdir ilə yeni folder (qovluq) yaradırıq',
        'ulink'  => [],
    ],
    [
        'name'   => 'touch folderName/fileName',
        'img_url' => './assets\img\Screenshot-2022-02-23-044713.png',
        'izah'   => 'touch ilə yeni fayl yaradırıq.<b><i> touch fileName</i> </b> yazaraq da istifadə edə bilərik.',
        'ulink'  => [],
    ],
    [
        'name'   => 'ls folderName/',
        'img_url' => './assets\img\Screenshot-2022-02-23-044733.png',
        'izah'   => 'bu yazılış ilə folderə daxil olmadan həmin folder içindəki fayl və qovluqları listələyirik',
        'ulink'  => [],
    ], 
    [
        'name'   => 'ümumi baxış',
        'img_url' => './assets\img\Screenshot-2022-02-23-044756.png',
        'izah'   => '',
        'ulink'  => [],
    ], 
    [
        'name'   => 'rm fileName',
        'img_url' => './assets\img\Screenshot-2022-02-23-044915.png',
        'izah'   => 'faylı silmək üçün istifadə olunur',
        'ulink'  => [],
    ], 
    [
        'name'   => 'cd ..',
        'img_url' => './assets\img\Screenshot-2022-02-23-044944.png',
        'izah'   => 'qovluqdan çıxmaq üçün istifadə olunur',
        'ulink'  => [],
    ], 
    [
        'name'   => 'rmdir folderName',
        'img_url' => './assets\img\Screenshot-2022-02-23-045037.png',
        'izah'   => 'folder`i (qovluğu) silmək üçün istifadə olunur',
        'ulink'  => [],
    ], 
    [
        'name'   => 'Yeni mühit yaradaq',
        'img_url' => './assets\img\Screenshot-2022-02-23-045148.png',
        'izah'   => '',
        'ulink'  => [],
    ], 
    [
        'name'   => 'rm -rf folderName',
        'img_url' => './assets\img\Screenshot-2022-02-23-045223.png',
        'izah'   => 'folder və içindəkiləri məcburi silir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git init',
        'img_url' => '',
        'izah'   => '.git folderi yaradır və folder daxilindəki dəyişiklikləri izləyir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git add .',
        'img_url' => '',
        'izah'   => 'bütün dəyişiklikləri local-dan stage mərhələsinə göndərir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git add fileName',
        'img_url' => '',
        'izah'   => 'yazılan faylı local-dan stage mərhələsinə göndərir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git add folderName',
        'img_url' => '',
        'izah'   => 'yazılan folder`i local-dan stage mərhələsinə göndərir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git commit -m "message"',
        'img_url' => '',
        'izah'   => 'stage`ə əlavə edilmiş dəyişikliyə commit əlavə edir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git branch',
        'img_url' => '',
        'izah'   => 'var olan branch`ları listələyir, aktiv olan branch`in qabağında asteriks işarəsi olur',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git branch branchName',
        'img_url' => '',
        'izah'   => 'yeni branc yaradır',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git push -u origin main',
        'img_url' => '',
        'izah'   => 'stage mərhələsində olan bütün dəyişiklikləri origin(qlobala) mərhələsinə göndərir, buradakı <b><i> main </i></b> branch adıdır.',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git status',
        'img_url' => '',
        'izah'   => 'local mərhələsi ilə stage mərhələsi arasındakı fərqləri göstərir',
        'ulink'  => [],
    ], 
    [
        'name'   => 'git log',
        'img_url' => '',
        'izah'   => 'stage mərhələsi ilə origin arasındakı fərqləri və var olan versiyaları göstərir',
        'ulink'  => [],
    ],
    [
        'name'   => 'git log --patch',
        'img_url' => '',
        'izah'   => 'stage mərhələsi ilə origin arasındakı fərqləri ətraflı göstərir',
        'ulink'  => [],
    ],
    [
        'name'   => 'git reset',
        'img_url' => '',
        'izah'   => 'Stage mərhələsinə göndərilmiş folder`i, faylı və ya commiti geri (locala) qaytarır.',
        'ulink'  => [],
    ],
    [
        'name'   => 'git diff',
        'img_url' => '',
        'izah'   => 'Əgər hər hansı faylda dəyişiklik etsək və bu localda olub stage-də olmasa git diff əmri ilə dəyişiklikləri görə bilərik.',
        'ulink'  => [],
    ],
    [
        'name'   => 'git diff --staged',
        'img_url' => '',
        'izah'   => 'stage ilə origin arasındakı fərqləri sətirbəsətir göstərir',
        'ulink'  => [],
    ],
    [
        'name'   => 'git rm fileName',
        'img_url' => '',
        'izah'   => 'Ya faylı silir və stage mərhələsinə faylın silindiyini bildirir ya da silinən faylı stage mərhələsinə bildirir. Eyni zamanda <b><i>git add fileName</i></b> də yaza bilərik.',
        'ulink'  => [],
    ],
    [
        'name'   => 'git rm -r folderName/',
        'img_url' => '',
        'izah'   => 'Rekursiv silmə işi üçün bu əmrdən istifadə olunur. İlk öncə folderin daxilindəki faylları silir. Daha sonra folderin özünü. -r yerinə -rf də yazmaq olur. Burdakı f isə faylları məcbur silmə əmridir.',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],
    [
        'name'   => '',
        'img_url' => '',
        'izah'   => '',
        'ulink'  => [],
    ],

];
