<?php 
$questions = [
    [
        'id' => 1,
        'header' => 'Windows əsaslı Git quraşdırması ilə Bash shell üçün standart mətn redaktoru nədir ?',
        'a' => 'Emacs',
        'b' => 'Vim',
        'c' => 'Notepad++',
        'd' => 'Bash',
        'correct' => 'b',
    ],
    [
        'id' => 2,
        'header' => 'Git`i kim icad etmişdir ?',
        'a' => 'Linus Torvalds',
        'b' => 'James Gosling',
        'c' => 'Alan Turing',
        'd' => 'Elon Musk',
        'correct' => 'a',
    ],
    [
        'id' => 3,
        'header' => 'Localda yeni git repozitorisi init etdikdən sonra və <b>git-quiz.html</b> adlı fayl yaratdıqdan sonra aşağıdakı əmrlərdən hansı verilsə işləməyəcək ?',
        'a' => 'git add git-quiz.html',
        'b' => 'git status',
        'c' => 'git add .',
        'd' => 'git commit -m "git-quiz web file added"',
        'correct' => 'd',
    ],
    [
        'id' => 4,
        'header' => 'Git nədir ?',
        'a' => 'Versiyaya nəzarət sistemi',
        'b' => 'Proqramlaşdırma dili',
        'c' => 'Uzaqdan depo platforması',
        'd' => 'Github`un ləqəbi (Başqa adı)',
        'correct' => 'a',
    ],
    [
        'id' => 5,
        'header' => 'Git`in quraşdırılmış verisyasını yoxlamaq üçün hansı əmri istifadə edirik ?',
        'a' => 'git -v',
        'b' => 'git --v',
        'c' => 'git --version',
        'd' => 'git -version',
        'correct' => 'c',
    ],
    [
        'id' => 6,
        'header' => 'Folder daxilindəki faylları gizli fayllar ilə birgə listləmək üçün hansı əmrdən istifadə olunur?',
        'a' => 'git ls',
        'b' => 'git ls -a',
        'c' => 'ls',
        'd' => 'ls -a',
        'correct' => 'd',
    ],
    [
        'id' => 7,
        'header' => '<b> /c/xampp/htdocs/Quiz </b> -path`indən <b> /c/xampp/htdocs</b> path-inə getmək üçün :',
        'a' => 'cd ./',
        'b' => 'cd ..',
        'c' => 'cd ../',
        'd' => 'cd .',
        'correct' => 'b',
    ],
    [
        'id' => 8,
        'header' => '<b>Git Bash</b> da terminal təmizləmək üçün hansı qısa yol doğrudur',
        'a' => 'CTRL + Z',
        'b' => 'CTRL + D',
        'c' => 'CTRL + L',
        'd' => 'CTRL + A',
        'correct' => 'c',
    ],
    [
        'id' => 9,
        'header' => 'Git Bash-də bütün komanda tarixçəsini təmizləmək üçün :',
        'a' => 'clear',
        'b' => 'git clear',
        'c' => 'git -clear',
        'd' => 'history -c',
        'correct' => 'd',
    ],
    [
        'id' => 10,
        'header' => 'ls myfolder/ əmrini daxil etdikdə :',
        'a' => 'Folderə daxil olmadan içərisindəki faylları listələyir',
        'b' => 'Folderə daxil olur,daha sonra qovluğun içərisində olan fayl və qovluqları listələyir',
        'c' => 'Folderə daxil olmadan içərisindəki fayl və qovluqları listələyir',
        'd' => 'Xəta verir!',
        'correct' => 'c',
    ],
    // [
    //     'id' => 11,
    //     'header' => 'Əmrlərdən hansı doğru deyil ?',
    //     'a' => 'git log --patch',
    //     'b' => 'git status',
    //     'c' => 'git diff --version',
    //     'd' => 'git add file.txt',
    //     'correct' => 'c',
    // ],
    // [
    //     'id' => 12,
    //     'header'=>'Fayl yaratmaq üçün :',
    //     'a'=>'mkdir',
    //     'b'=>'touch',
    //     'c'=>'git init',
    //     'd'=>'pwd',
    //     'correct'=>'b',
    // ],
    // [
    //     'id' => 13,
    //     'header'=>'Fayl silmək üçün əmrlərdən hansı doğrudur ?',
    //     'a'=>'rmdir',
    //     'b'=>'rm fileName',
    //     'c'=>'rmdir fileName',
    //     'd'=>'ls',
    //     'correct'=>'',
    // ],
    // [
    //     'id' => 14,
    //     'header' => 'Folder silmək üçün hansı əmr doğrudur :',
    //     'a' => 'rm folderName',
    //     'b' => 'rm -r folderName',
    //     'c' => 'rmdir folderName',
    //     'd' => 'rm',
    //     'correct' => 'c',
    // ],
    // [
    //     'id' => null,
    //     'header' => '',
    //     'a' => '',
    //     'b' => '',
    //     'c' => '',
    //     'd' => '',
    //     'correct' => '',
    // ],
    // [
    //     'id' => null,
    //     'header' => '',
    //     'a' => '',
    //     'b' => '',
    //     'c' => '',
    //     'd' => '',
    //     'correct' => '',
    // ],
    // [
    //     'id' => null,
    //     'header' => '',
    //     'a' => '',
    //     'b' => '',
    //     'c' => '',
    //     'd' => '',
    //     'correct' => '',
    // ],
    
];